# Generated by Django 6.0 on 2026-01-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trolley',
            name='qr_code_data',
            field=models.CharField(blank=True, help_text='Data encoded in QR code', max_length=255),
        ),
    ]
