# Generated by Django 6.0 on 2026-01-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleys', '0002_trolley_qr_code_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trolley',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When trolley was assigned to user', null=True),
        ),
        migrations.AddField(
            model_name='trolley',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User currently using this trolley', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trolleys', to=settings.AUTH_USER_MODEL),
        ),
    ]
